name: CI - FastAPI Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run simple test
    - name: Run tests
      run: |
        echo "Running placeholder test..."
        python -c "print('Hello World test passed!')"

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t fastapi-hello .
